### PR TITLE
Celery priority queues

### PR DESCRIPTION
**Pull request by emmanvg**
Defines three queues where Tasks can be routed to.

### CODE REVIEW

**Comment by emmanvg** [comment]
We might need to look at this more closely. I was trying to test locally and was getting hung up on test_api.py "test_get_nonexistent_report"

**Comment by emmanvg** [comment]
It should be good for review now...

**Comment by ptcNOP** [comment]
Everything finishes as expected. Do you have a good method to test the priority portion?

**Comment by emmanvg** [comment]
I don't think we can test the Celery Queues/Workers explicitly since the test harness is not deploying a distributed instance of MultiScanner. At most, we can mock how each task gets routed into each "queue".

**Pull request merged**
