### PR TITLE
Give a warning if the given file(s) weren't found

### PR DESCRIPTION
**Pull request by clenk**
If I fat-finger a filename, I'd like to know about it instead of MultiScanner silently doing nothing.

### CODE REVIEW

**Comment by clenk** [comment]
That's a good point; the end result will be the same but it'll save a couple cycles.

**Comment by awest1339** [comment]
@Drewsif this look good to you?

**Comment by Drewsif** [comment]
Looks good to me. It would be nice if it also warned you if command line files/folders weren't there.

**Comment by awest1339** [comment]
@Drewsif I believe this PR does give a warning if it doesn't find the files? Not sure what you mean.

Planning on merging unless I hear otherwise :)

**Pull request merged**
