### PR TITLE
Add flake8 to CI and bring everything in line with pep8

### PR DESCRIPTION
**Pull request by ptcNOP**
Some things had been committed directly to master (instead of feature-celery) and didn't get the pep8 cleanup. This brings everything in master in line with our flake8 config _except for_ [this](https://github.com/ptcNOP/multiscanner/blob/1c05909c4a699addd202b3cb2ca43a6147eea84a/utils/nsrl_parse.py#L33). ~~, which I don't think is actually py3 compatible.~~

### CODE REVIEW

**Comment by ptcNOP** [comment]
Alternative to pylint (#70). Do you have a preference for pylint over flake8?

**Comment by clenk** [comment]
I think flake8 might be faster, but pylint is generally more popular, more configurable, and can give more detailed results.

**Comment by ptcNOP** [comment]
I'm not opposed to pylint, but do you know of a sane pylintrc?...the output is a little overwhelming. 

Also, since multiscanner doesn't exactly follow python packing convention, I think we need to pass each .py to pylint; it doesn't seem to just recurse directory structures.

**Comment by ptcNOP** [comment]
@awest1339, pylint vs. flake8?

**Comment by Drewsif** [comment]
I have no preference between the two

**Comment by awest1339** [comment]
I don't have a preference either way. I agree that pylint is maybe excessively verbose, so maybe flake8 is the better short term solution for us now?

**Pull request merged**
