### PR TITLE
feature/metricbeat cleanup

### PR DESCRIPTION
**Pull request by ptcNOP**
Add periodic celery task to delete older metricbeat indices. Defaults to 7 days.

### CODE REVIEW

**Comment by ptcNOP** [comment]
Oops, this has some of my other commit that haven't been pulled in yet.

**Comment by ptcNOP** [comment]
This is breaking because the `elasticsearch-curator` dependency was added to `setup.py` instead of `requirements.txt`. Where do we think it actually belongs?

**Comment by awest1339** [comment]
Can we rebase this on latest master?

**Comment by ptcNOP** [comment]
I don't think a rebase is going to do anything. What result are you looking for?

**Comment by ptcNOP** [comment]
Also, we can remove the elasticsearch-curator dependency, but it's doing a lot under the hood. Without re-implementing all of that, the best solution I can think of is:

- Get current date
- Create list of dates by subtracting [1..days] from current date
- For each date in list of dates, try to delete metricbeat-<date>

This would be okay if it ran everyday as expected, but if it missed a day, that index would remain.

**Comment by ptcNOP** [comment]
I went ahead and merge master back into my branch (with no conflicts). Is that what you were looking for or you do you just want me to open a new PR?

**Comment by awest1339** [comment]
Nope this looks great. Just didn't like how it had a bunch of extra files changed in it.

Thanks!

**Comment by awest1339** [comment]
Should we make the number of days a config option in config.ini?

**Comment by ptcNOP** [comment]
Do you think it belongs in `config.ini` or in [here](https://github.com/ptcNOP/multiscanner/blob/feature/metricbeat-cleanup/storage/elasticsearch_storage.py#L70)?

**Comment by awest1339** [comment]
So i think they should be in the storage.ini. Which means that it should be in the ElasticSearch default conf as well

**Comment by ptcNOP** [comment]
@awest1339, how's this?

**Comment by awest1339** [comment]
This looks good to me code wise. I will test then merge

**Pull request merged**
