### PR TITLE
WIP: Refactor Multiscanner to better support python packaging

### PR DESCRIPTION
**Pull request by ptcNOP**
The main goal of this pull request is to reorganize the Multiscanner repo to take advantage of standard Python packaging. This allows improved package imports that do not require manipulating the system path.

Most changes affect how previously written code is imported and not the actual functionality of the code.

### CODE REVIEW

**Comment by clenk** [comment]
For setup.py vs requirements.txt, I've seen a lot of projects put development, documentation & testing requirements in the text file, and requirements for using/running the package in setup.py. You could also instead put the "development" requirements in "extras_require['dev']" [like Flask does](https://github.com/pallets/flask/blob/master/setup.py#L43).

**Comment by emmanvg** [comment]
@clenk @ptcNOP it should be ready for comments/merge.

**Comment by ptcNOP** [comment]
`AttributeError: module '__init__' has no attribute 'check'`

We are grabbing __init__.py files as MS modules. Need to filter them out.

**Comment by ptcNOP** [comment]
`FileNotFoundError: [Errno 2] No such file or directory: '/Users/pcopeland/.multiscanner/etc/yarasigs'`

YARA signatures aren't added to the config directory.

**Comment by ptcNOP** [comment]
`FileNotFoundError: [Errno 2] No such file or directory: '~/.multiscanner/etc/yarasigs'`

YARA sigs are not being added to config directory.

**Pull request merged**
